# Generated by Django 5.0.1 on 2024-05-29 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_saleitem_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='price_difference',
        ),
    ]
